# Install Scikit-learn

`pip install scikit-learn`

# Split data

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

x, y = np.arange(20).reshape((10, 2)), np.arange(10)

print('before splitting......')

print("x: {}\n".format(x))
print("y: {}\n".format(y))

print("shape of x: {}".format(x.shape))
print("shape of y: {}\n".format(y.shape))

# random_state = 1
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state = 1)
print('after splitting......')

print("x_train: {}\n".format(x_train))
print("x_test: {}\n".format(x_test))

print("y_train: {}\n".format(y_train))
print("y_test: {}\n".format(y_test))

before splitting......
x: [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

y: [0 1 2 3 4 5 6 7 8 9]

shape of x: (10, 2)
shape of y: (10,)

after splitting......
x_train: [[ 8  9]
 [ 0  1]
 [ 6  7]
 [ 2  3]
 [14 15]
 [16 17]
 [10 11]]

x_test: [[ 4  5]
 [18 19]
 [12 13]]

y_train: [4 0 3 1 7 8 5]

y_test: [2 9 6]



# Preprocessing Data

## Standardize data into zero mean and unit std

In [1]:
from sklearn import preprocessing
import numpy as np

x_train = np.array([[ 100., -1.,  2.],
                    [ 900.,  0.,  0.],
                    [ 200.,  1., -1.]])


print("mean of x_train: {}".format(x_train.mean(axis=0)))
print("std of x_train: {}\n".format(x_train.std(axis=0)))


scaler = preprocessing.StandardScaler().fit(x_train)

print("mean of x_scale: {}".format(scaler.mean_))
print("std of x_scale: {}\n".format(scaler.scale_))

# apply mean and std to standardize data
x_train = scaler.transform(x_train)

print("after standardiztion......")
print('x_train: {}'.format(x_train))


x_test = np.array([[-1., 1., 0.]])
print("apply same mean and std to new data(test data)\n")

x_test = scaler.transform(x_test)
print('x_test: {}'.format(x_test))



mean of x_train: [  4.00000000e+02   0.00000000e+00   3.33333333e-01]
std of x_train: [ 355.9026084     0.81649658    1.24721913]

mean of x_scale: [  4.00000000e+02   0.00000000e+00   3.33333333e-01]
std of x_scale: [ 355.9026084     0.81649658    1.24721913]

after standardiztion......
x_train: [[-0.84292723 -1.22474487  1.33630621]
 [ 1.40487872  0.         -0.26726124]
 [-0.56195149  1.22474487 -1.06904497]]
apply same mean and std to new data(test data)

x_test: [[-1.12671273  1.22474487 -0.26726124]]


## Standardize data into a range

In [4]:
from sklearn import preprocessing
import numpy as np

x_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

scaler = preprocessing.MinMaxScaler().fit(x_train)
x_train = scaler.transform(x_train)

print("after standardiztion......")
print('x_train: {}'.format(x_train))


x_test = np.array([[ -3., -1.,  4.]])
print("apply same transformation to new data(test data)\n")

x_test = scaler.transform(x_test)
print('x_test: {}'.format(x_test))

after standardiztion......
x_train: [[ 0.5         0.          1.        ]
 [ 1.          0.5         0.33333333]
 [ 0.          1.          0.        ]]
apply same transformation to new data(test data)

x_test: [[-1.5         0.          1.66666667]]


# Evaluate Result

In [3]:
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix

y_test = [0, 1, 0 , 1, 0]
y_pred = [1, 0, 0 , 1, 0]

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

accuracy = accuracy_score(y_test, y_pred)
num_correct_samples = accuracy_score(y_test, y_pred, normalize=False)
con_matrix = confusion_matrix(y_test, y_pred)


print("Mean squared error: {}".format(mse))
print('r2 score: {}'.format(r2))
print('number of correct sample: {}'.format(num_correct_samples))
print('accuracy: {}'.format(accuracy))
print('confusion matrix: {}'.format(con_matrix))

Mean squared error: 0.4
r2 score: -0.6666666666666665
number of correct sample: 3
accuracy: 0.6
confusion matrix: [[2 1]
 [1 1]]


# Kaggle Introduction

kaggle website: https://www.kaggle.com/  
kaggle api: https://github.com/Kaggle/kaggle-api