In [ ]:
from google.colab import drive #從colab連接到自己的雲端硬碟。
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# 今天的目標
- 寫numpy練習題

## 第一題
- 計算兩個數組a和b之間的歐式距離。

  - 利用`np.linalg.norm()`

answer1: 6.708203932499369


In [2]:
#1
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
answer1 = np.linalg.norm(a-b)
print("answer1:",answer1)

answer1: 6.708203932499369


## 第二題
- 將a數列的第1列第5列互換後,第2列第3列互換。

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
answer2:
 [[20 21 22 23 24]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [12]:
#2
a = np.arange(25).reshape(5,5)
print(a)
answer2 = a[[4,2,1,3,0]]
print("answer2:\n",answer2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
answer2:
 [[20 21 22 23 24]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


## 第三題
- 建出規定的數列在不使用暴力法(直接宣告的情況下也就是只能使用numpy函數和輸入數組a)
  - `[1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3]`
  - 利用 `np.r_`、`np.repeat()`、`np.tile()`
    - `np.r_[a,b,c...]`:可以拼接多個數組，要求待拼接的多個數組的列數必須相同
    - `np.repeat()`:對數列中的元素進行連續重複複製
    - `np.tile()`:對整個數列進行複製拼接

answer3: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [17]:
#3

a = np.array([1,2,3])
# print(np.repeat(a,3))
# print(np.tile(a,3))
answer3 = np.r_[np.repeat(a,3),np.tile(a,3)]
print("answer3:",answer3)

answer3: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## 第四題
- 在一維numpy數列a中查找所有峰值。峰值是兩側較小值包圍的點。
  - 利用`np.diff()`、`np.sign()`、`np.where()`
    - `np.diff()`:將數列中每個元素相減(下一個減前一個),結果存成一個新的數列
    - `np.sign`:比1大變1,0還是0,比1小的數變-1

[ 2  4 -6  1  4 -6  1]
[ 1  1 -1  1  1 -1  1]
[ 0 -2  2  0 -2  2]
answer4: [2 5]


In [33]:
#4

a = np.array([1,3,7,1,2,6,0,1])
print(np.diff(a))
print(np.sign(np.diff(a)))
print(np.diff(np.sign(np.diff(a))))
signed_doublediff = np.diff(np.sign(np.diff(a)))
peak_location = np.where(signed_doublediff==-2)
answer4 = peak_location
print("answer4:",answer4[0]+1)

[ 2  4 -6  1  4 -6  1]
[ 1  1 -1  1  1 -1  1]
[ 0 -2  2  0 -2  2]
answer4: [2 5]


## 第五題
- 獲取前天、後天的日期
  - 利用`np.timedelta64()`
  - `np.timedelta64()`:一個時間的伸縮量,可以用來對np.datetime64()進行運算(+,-,...)


answer5_today: 2020-12-17
answer5_before_yesterday: 2020-12-15
answer5_after_tomorrow: 2020-12-19


In [36]:
#5

answer5_today = np.datetime64('2020-12-17', 'D')
answer5_before_yesterday = answer5_today + np.timedelta64(-2,'D')
answer5_after_tomorrow = answer5_today + np.timedelta64(2,'D')
print("answer5_today:",answer5_today)
print("answer5_before_yesterday:",answer5_before_yesterday)
print("answer5_after_tomorrow:",answer5_after_tomorrow)

answer5_today: 2020-12-17
answer5_before_yesterday: 2020-12-15
answer5_after_tomorrow: 2020-12-19


## 第六題
- 找出x數列中數字1重複了第5次的那個索引
  - 利用`np.where()`

[ 0  2  3  7  8 10 11]
answer6: 8


In [48]:
#6
x = np.array([1,2,1,1,3,4,3,1,1,2,1,1,2])
n = 5
answer6 = np.where(x==1)
print("answer6:",answer6[0][n-1])

answer6: 8


##第七題
- 刪除一維numpy數列的所有nan值
  - 利用`~`、`np.isnan()`
  - `~`:將所有boolean值顛倒,如`[true,false]`->`[false,true]`


answer7: [1. 2. 3. 5. 6. 7.]


In [52]:
#7
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
# print(np.isnan(a))
# print(~np.isnan(a))
answer7 = a[np.where(~np.isnan(a)==True)]
print("answer7:",answer7)

answer7: [1. 2. 3. 5. 6. 7.]


##第八題
- 給一個不連續的日期數列dates。通過填補缺失的日期，使其成為連續的日期數列。
  
  - 利用`np.arange()、np.insert()`

input dates: ['2020-11-01' '2020-11-03' '2020-11-05' '2020-11-07' '2020-11-09'
 '2020-11-11' '2020-11-13' '2020-11-15' '2020-11-17' '2020-11-19'
 '2020-11-21' '2020-11-23']
['2020-11-02' '2020-11-04' '2020-11-06' '2020-11-08' '2020-11-10'
 '2020-11-12' '2020-11-14' '2020-11-16' '2020-11-18' '2020-11-20'
 '2020-11-22' '2020-11-24']
answer8: ['2020-11-01' '2020-11-02' '2020-11-03' '2020-11-04' '2020-11-05'
 '2020-11-06' '2020-11-07' '2020-11-08' '2020-11-09' '2020-11-10'
 '2020-11-11' '2020-11-12' '2020-11-13' '2020-11-14' '2020-11-15'
 '2020-11-16' '2020-11-17' '2020-11-18' '2020-11-19' '2020-11-20'
 '2020-11-21' '2020-11-22' '2020-11-23' '2020-11-24']


In [54]:
#8
dates = np.arange(np.datetime64('2020-11-01'),np.datetime64('2020-11-25'),2)
print("input dates:",dates)
answer8 = dates
# dates2 =      #創建出1~25日所有缺失的日期的ndarray
#print(dates2)
# j = 0
# for i in range(0,len(dates2)):
#   answer8 = 
#   j = 
# print("answer8:",answer8)

input dates: ['2020-11-01' '2020-11-03' '2020-11-05' '2020-11-07' '2020-11-09'
 '2020-11-11' '2020-11-13' '2020-11-15' '2020-11-17' '2020-11-19'
 '2020-11-21' '2020-11-23']
